name: Continuous build and release docker image
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: go test -v -race ./...
      - run: go vet ./...
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: timo-reymann/docker-semantic-release-gh-action@v4
        with:
          image: timoreymann/github-serve-flow
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
